# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 87b884e0fb8cc24f70c20820f88e19387737ab96782cf5eccc439f5b74ef3625a045f092e6e18227db124afa0bb9a76220f0a0244213c2061319e7a631b4bdb0

test:
  secret_key_base: 8aaf0c3631fb063630c1fe7adaee40410c93c1e93a96edb598f6a5e68e5604ed02316dcca1da39873bffe2bd76c58495147deb13df4d1c1aff9d9894e130b76e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
